/**
 * Utility for generating random Sonifyr taglines for Spotify descriptions
 */

const SONIFYR_TAGLINES = [
  "Sonify Your Stars. Stream Your Story.",
  "Your Horoscope. Your Soundtrack.",  
  "Astrology That Speaks in Songs.",
  "Let the Planets Pick the Playlist.",
  "Daily Vibes, Written in the Stars.",
  "A New Way to Hear the Universe.",
  "From Transit to Track — Feel the Cosmic Flow.",
  "Music That Moves with Your Moon.",
  "Your Chart. Your Sound. Your Week in Vibes.",
  "Zodiac to Spotify — Instantly."
];

/**
 * Get a random Sonifyr tagline for Spotify playlist descriptions
 */
export function getRandomTagline(): string {
  const randomIndex = Math.floor(Math.random() * SONIFYR_TAGLINES.length);
  return SONIFYR_TAGLINES[randomIndex];
}

/**
 * Generate personalized Spotify playlist description
 * @param sunSign - User's sun sign
 * @param moonSign - User's moon sign (optional)
 * @param planetarySummary - Brief summary of planetary energies
 * @param fallbackDescription - Fallback if astrological data unavailable
 */
export function generatePersonalizedDescription(
  sunSign?: string,
  moonSign?: string,
  planetarySummary?: string,
  fallbackDescription?: string
): string {
  const tagline = getRandomTagline();
  
  // If we have sun sign, create personalized description
  if (sunSign) {
    const signDescriptor = moonSign 
      ? `This ${sunSign} - ${moonSign} Moon playlist`
      : `This ${sunSign} playlist`;
    
    const energyDescription = planetarySummary 
      ? planetarySummary
      : "embraces this week's celestial energies, blending cosmic influences with melodies that resonate with your personal astrological essence";
      
    return `${signDescriptor} ${energyDescription}. - Generated by Sonifyr (${tagline})`;
  }
  
  // Fallback for when astrological data isn't available
  return `${fallbackDescription || "Cosmic playlist curated by AI based on astrological insights"}. - Generated by Sonifyr (${tagline})`;
}